abxy_mode: Switch
auto_disconnect_days: 0
auto_disconnect_enabled: false
auto_disconnect_hours: 0
auto_disconnect_minutes: 0
button_remaps:
  ps:
    c_mapping: Default
    capt_mapping: Capture
    gl_mapping: PS_L_Touch
    gr_mapping: PS_R_Touch
    home_mapping: Default
    sll_mapping: Default
    slr_mapping: PS_R_Touch
    srl_mapping: PS_L_Touch
    srr_mapping: Default
  switch2:
    c_mapping: Default
    capt_mapping: Capture
    gl_mapping: GL
    gr_mapping: GR
    home_mapping: Default
    sll_mapping: Default
    slr_mapping: GR
    srl_mapping: GL
    srr_mapping: Default
  xbox:
    c_mapping: Default
    capt_mapping: Capture
    gl_mapping: Default
    gr_mapping: Default
    home_mapping: Default
    sll_mapping: Default
    slr_mapping: Default
    srl_mapping: Default
    srr_mapping: Default
c_mapping: Default
calibration_data: {}
capt_mapping: Capture
driver_installed: false
driver_type: WinUHid
gl_mapping: PS_L_Touch
gr_mapping: PS_R_Touch
gyro_activation_mode: Hold
gyro_bias_l:
- 0.0
- 0.0
- 0.0
gyro_bias_r:
- 0.0
- 0.0
- 0.0
gyro_mode: World
gyro_sensitivity: 4.0
home_mapping: Default
joycon_hold_mode: {}
mag_calibration_data: {}
merged_gyro_side: {}
mouse:
  enabled: true
  sensitivity: 4.0
open_when_startup: false
rumble_mode: Switch
simulation_mode: PS5
sll_mapping: Default
slr_mapping: PS_R_Touch
srl_mapping: PS_L_Touch
srr_mapping: Default
stabilized_gyro: true
start_minimized: false
steam_roll_compensation: false
stick_mouse_sensitivity: 5.0
stick_r_bias:
- 0.0
- 0.0
vibration_frequency: 10
vibration_strength: 5
vibration_strength_switch: 5
vibration_strength_xbox: 5
vigembus_installed: true
vigembus_sim_mode: Xbox360
virtual_gyro_soft_deadzone: 0.0
window_height: 1080
window_width: 1240
winuhid_sim_mode: PS5
