abxy_mode: Switch
auto_disconnect_days: 0
auto_disconnect_enabled: false
auto_disconnect_hours: 0
auto_disconnect_minutes: 0
c_mapping: Default
calibration_data:
  E0:EF:BF:81:06:9F:
  - 5.419047619047619
  - -16.057142857142857
  - -0.012698412698412698
capt_mapping: Capture
driver_installed: false
driver_type: WinUHid
gl_mapping: PS_L_Touch
gr_mapping: PS_R_Touch
gyro_activation_mode: Hold
gyro_bias_l:
- 0.0
- 0.0
- 0.0
gyro_bias_r:
- 5.419047619047619
- -16.057142857142857
- -0.012698412698412698
gyro_mode: World
gyro_sensitivity: 3.0
home_mapping: Default
joycon_hold_mode:
  E0:EF:BF:F0:0E:17: Horizontal
mag_calibration_data:
  E0:EF:BF:81:06:9F:
  - 130.5
  - 85.5
  - 18.0
merged_gyro_side: {}
mouse:
  enabled: true
  sensitivity: 5.0
open_when_startup: false
rumble_mode: Switch
simulation_mode: PS5
sll_mapping: Default
slr_mapping: PS_R_Touch
srl_mapping: PS_L_Touch
srr_mapping: Default
stabilized_gyro: true
start_minimized: false
steam_roll_compensation: false
stick_mouse_sensitivity: 5.0
stick_r_bias:
- 0.0
- 0.0
vibration_frequency: 10
vibration_strength: 5
vibration_strength_switch: 5
vibration_strength_xbox: 5
vigembus_installed: true
vigembus_sim_mode: Xbox360
virtual_gyro_soft_deadzone: 0.0
window_height: 1080
window_width: 1240
winuhid_sim_mode: PS5
